version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - cars-mongo
      - cars-redis
      - cars-nats
  cars-mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  cars-redis:
    image: redis:latest
    ports:
      - "6379:6379"
  cars-nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"

